### ISSUE TITLE
Docker: SQLPad - Forbidden error message

### ISSUE THREAD

**Issue by sjaak8000** [sqlpad/sqlpad#931] opened 2021-01-07 11:39 UTC
I'm running SQLPad on Docker, when trying to log in the error message: "Username or password incorrect" occurs.
And during signup a "forbidden" message is displayed.
 - Login or signup is both not working.

I'm passing these environment options to the Docker container.
```
# Email address to give admin permissions to
SQLPAD_ADMIN=""

# Password to set for admin email address on application start. Requires `admin` setting to also be provided.
SQLPAD_ADMIN_PASSWORD=""
```

**Comment by sjaak8000** [comment] 2021-01-07 21:23
I did some further testing today. The issue seems to occur starting from the 6.x release of SQLPad. I tested it with version 5 and version 5.8, and the issue "forbidden" did not occur.

**Comment by rickbergfalk** [comment] 2021-01-14 22:39
I'm unable to reproduce. 6.x releases are working just fine for me. 

Is it possible to set log levels to debug and see if anything interesting is showing up?

**Comment by rickbergfalk** [comment] 2021-03-12 05:41
@sjaak8000 going to close this issue out. If you're still having the forbidden issue let me know.

**Closed by rickbergfalk** 2021-03-12 05:41 UTC

**Comment by ghoshsanjoy78** [comment] 2021-04-16 20:20
I am having this issue as well. Exact same steps

**Comment by rickbergfalk** [comment] 2021-04-17 16:48
@ghoshsanjoy78 was this happening for you with move from v5 to v6?

**Comment by sc911** [comment] 2021-05-04 15:07
You need to set the the mail-address without quotes:
```
SQLPAD_ADMIN=mail@domain.tld
```
Otherwise quotes will be included so I guess you could login using `"mail@domain.tld"` but not having tried that...
So a stripped down docker-compose.yml would look like this:
```
version: "3.5"
services:
  sqlpad:
    image: "sqlpad/sqlpad:6.6.0"
    environment:
      - SQLPAD_ADMIN=mail@domain.tld
    volumes:
      - "[...]:/var/lib/sqlpad"

```

**Comment by wztan004** [comment] 2021-07-24 15:44
Same issue as https://github.com/sqlpad/sqlpad/issues/931#issuecomment-756393476

During signup a "forbidden" message is displayed. This happened on the latest version and also on 6.0.0. I then switched to 5.8.4 and there isn't this error message.
Last line of error: `{"level":30,"time":"2021-07-24T15:39:54.153Z","pid":1,"hostname":"5690f77156d3","name":"sqlpad-web","req":{"id":10,"method":"POST","url":"/api/signup"},"res":{"statusCode":403},"responseTime":265,"msg":"request completed"}`

![image](https://user-images.githubusercontent.com/42290390/126873739-bb3d49c2-2f57-455a-8cd4-cf4499434d3a.png)

**Comment by sarathsaleem** [comment] 2021-08-07 22:22
Same issue on latest docker

**Comment by Blue-Comet** [comment] 2024-01-04 16:45
Has this problem been solved? As of now
You still cannot sign up as Forbidden in latest, 7, or 6 versions.
